<Project>
  <Target Name="DisplayBuildInfo" BeforeTargets="Build">
    <Message Importance="high" Text="Building $(MSBuildProjectName) - $(Configuration) - $(TargetFramework)" />
  </Target>

  <Target Name="CleanArtifacts" BeforeTargets="Clean">
    <RemoveDir Directories="$(BaseOutputPath)" Condition="Exists('$(BaseOutputPath)')" />
    <RemoveDir Directories="$(BaseIntermediateOutputPath)" Condition="Exists('$(BaseIntermediateOutputPath)')" />
  </Target>
</Project>
